import raw from './timeline.json';

export type Word = {
	t: string;
	start: number;
	end: number;
	em?: boolean;
	brand?: boolean;
	num?: boolean;
	lineBreak?: boolean;
};
export type Line = {id: string; scene: string; start: number; end: number; text: string; words: Word[]};
export type Span = {id: string; start: number; end: number};

export type Timeline = {
	fps: number;
	bpm: number;
	beat: number;
	duration: number;
	durationInFrames: number;
	lines: Line[];
	scenes: Span[];
	sections: Span[];
	events: Record<string, number | number[]>;
	sfx: {type: string; t: number; gain: number; pitch: number}[];
	kicks?: number[];
	levels?: number[][];
};

/** Generated by audio/build_vo.py (+ music.py kicks, mix.py levels) from the real voice recording. */
export const timeline = raw as unknown as Timeline;

export const line = (id: string): Line => {
	const l = timeline.lines.find((x) => x.id === id);
	if (!l) throw new Error(`No line "${id}"`);
	return l;
};

export const scene = (id: string): Span => {
	const s = timeline.scenes.find((x) => x.id === id);
	if (!s) throw new Error(`No scene "${id}"`);
	return s;
};

export const ev = (key: string): number => timeline.events[key] as number;
export const evs = (key: string): number[] => timeline.events[key] as number[];

/** Start time (s) of word `i` of line `id`. */
export const wordAt = (id: string, i: number): number => line(id).words[i].start;
